FROM node:18-alpine AS development
ENV NODE_ENV development
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY ./frontend/package.json .

RUN yarn install
# Copy app files
COPY ./frontend .
# Expose port
# EXPOSE 3000
# Start the app
CMD [ "yarn", "start" ]