services:
  valhalla:
    image: transit-drivecycle-valhalla
    ports:
      - 8002:8002
    build:
      context: .
      dockerfile: valhalla/Dockerfile
    volumes:
      - ./calgary:/custom_files
    environment:
      - server_threads=2  # determines how many threads will be used to run the valhalla server
      - use_tiles_ignore_pbf=True  # load existing valhalla_tiles.tar directly
      - build_elevation=True  # build elevation with "True" or "Force": will download only the elevation for areas covered by the graph tiles
      - build_admins=False  # build admins db with "True" or "Force"
      - build_time_zones=False  # build timezone db with "True" or "Force"
      - build_tar=True  # build an indexed tar file from the tile_dir for faster graph loading times
      - force_rebuild=True  # forces a rebuild of the routing tiles with "True"
  drivecycleapi:
    image: transit-drivecycle-api
    ports:
      - 81:81
    build:
      context: .
      dockerfile: drivecycleapi/Dockerfile
    depends_on:
      - valhalla
    volumes:
      - ./drivecycleapi/app:/code/app
    command: "uvicorn app.main:app --host 0.0.0.0 --port 81 --reload"
  frontend-dev:
    image: frontend-dev
    ports:
      - 80:80
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - drivecycleapi
    volumes:
      - ./frontend/site:/usr/share/nginx/html

networks:
  default:
    name: transitdrivecycle-dev-network