services:
  valhalla:
    container_name: drivecycle-valhalla
    image: saadiqm.azurecr.io/drivecycle-valhalla
    build:
      context: .
      dockerfile: valhalla/Dockerfile
  drivecycleapi:
    container_name: drivecycle-api
    image: saadiqm.azurecr.io/drivecycle-api
    build:
      context: .
      dockerfile: drivecycleapi/Dockerfile
    depends_on:
      - valhalla
  frontend-react-prod:
    container_name: frontend-react-prod
    image: saadiqm.azurecr.io/frontend-react-prod
    ports:
      - 80:80
    build:
      context: .
      dockerfile: frontend-react/Dockerfile
    depends_on:
      - drivecycleapi
    domainname: "drivecycle"
networks:
  default:
    name: transitdrivecycle-prod-network