services:
  valhalla:
    container_name: drivecycle-valhalla-prod
    image: drivecycle-valhalla-prod
    build:
      context: ./valhalla
  drivecycleapi:
    container_name: drivecycle-api-prod
    image: drivecycle-api-prod
    build:
      context: ./drivecycleapi
    depends_on:
      - valhalla
  frontend-react-prod:
    container_name: frontend-react-prod
    image: frontend-prod
    ports:
      - 80:80
    build:
      context: ./frontend
    depends_on:
      - drivecycleapi
    domainname: "drivecycle"
networks:
  default:
    name: transitdrivecycle-prod-network