services:
  valhalla:
    container_name: drivecycle-valhalla-dev
    build:
      context: .
      dockerfile: valhalla/Dockerfile
    ports:
      - 8002:8002
    volumes:
      - ./valhalla/data:/custom_files
    environment:
      - server_threads=2  # determines how many threads will be used to run the valhalla server
      - use_tiles_ignore_pbf=True  # load existing valhalla_tiles.tar directly
      - build_elevation=True  # build elevation with "True" or "Force": will download only the elevation for areas covered by the graph tiles
      - build_admins=False  # build admins db with "True" or "Force"
      - build_time_zones=False  # build timezone db with "True" or "Force"
      - build_tar=True  # build an indexed tar file from the tile_dir for faster graph loading times
      - force_rebuild=False  # forces a rebuild of the routing tiles with "True"
  drivecycleapi:
    container_name: drivecycle-api-dev
    image: drivecycle-api-dev
    ports:
      - 81:81
    build:
      context: .
      dockerfile: drivecycleapi/Dockerfile-dev
    depends_on:
      - valhalla
    environment:
      - POSTGRES_DB=postgis
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - SRID=3402
    volumes:
      - ./drivecycleapi/app:/code/app
    # command: ["./wait-for-it.sh", "-t", "240", "-h", "database", "-p", "5432", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "81", "--reload"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "81", "--reload"]
  frontend-prod:
    container_name: frontend-prod
    image: frontend-prod
    ports:
      - 80:80
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - drivecycleapi
      - valhalla
  frontend-dev:
    container_name: frontend-dev
    image: frontend-dev
    ports:
      - 3000:3000
    build:
      context: .
      target: development
      dockerfile: frontend/Dockerfile-dev
    depends_on:
      - drivecycleapi
      - valhalla
    volumes:
      - ./frontend/src:/app/src
  database:
    container_name: transit-drivecycle-db
    image: transit-drivecycle-db
    build:
      context: .
      dockerfile: database/Dockerfile
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DB=postgis
    ports:
      - "5432:5432"
    volumes:
      - ./transit-drivecycle-pgdata:/var/lib/postgresql
  gtfs:
    container_name: transit-drivecycle-gtfs
    image: transit-drivecycle-gtfs
    build:
      context: .
      dockerfile: gtfs/Dockerfile
    environment:
      - PGUSER=username
      - PGPORT=5432
      - PGPASSWORD=password
      - PGHOST=database
      - PGDATABASE=postgis
    volumes:
      - ./gtfs/calgary:/gtfs
    depends_on:
      - database
volumes:
  transit-drivecycle-pgdata:  
networks:
  default:
    name: transitdrivecycle-dev-network