FROM python:3.9-slim

RUN apt-get update && apt-get install -y git

WORKDIR /code

COPY ./drivecycleapi/requirements.txt /code/requirements.txt
COPY ./scripts/wait-for-it.sh .

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
