FROM node:14-alpine AS development
ENV NODE_ENV development
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY ./frontend-react/package.json .
COPY ./frontend-react/package-lock.json .

RUN npm install
# Copy app files
COPY ./frontend-react .
# Expose port
EXPOSE 3000
# Start the app
CMD [ "npm", "start" ]