#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo $1

    echo -n \
        "Usage: $(basename "$0") [--detached]
Runs the development server and database.

--detached: Run in detached mode.
"
}

while [[ "$#" > 0 ]]; do case $1 in
  --detached) DETACHED_ARG="--detach"; shift;;
  --help) usage; exit 0; shift;;
  *) break;;
esac; done

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    # Execute in subshell to avoid leaking exported env vars.
        docker-compose \
            -f docker-compose.yml \
            run --rm --service-ports \
            frontend-react
fi